### ISSUE TITLE
Consider using HypergeometricFunctions.jl

### ISSUE THREAD

**Issue by oscardssmith** [JuliaMath/Bessels.jl#16]
There might be cases where this is the best way to compute bessel functions.

**Comment by heltonmc** [comment]
Yes I've been looking into those for the generic `besselj` and `bessely`. I've been struggling to find an implementation I'm happy with though.

In general I've found that they are reasonably convergent when `x < nu`.  But, they do not converge very quickly when x is around nu or larger. I've been using [HypergeometricFunctions.jl](https://github.com/JuliaMath/HypergeometricFunctions.jl) specifically `drummond0F1`. I'm not for sure how mature that package is but in general it is a really good fall back. This issue https://github.com/JuliaMath/HypergeometricFunctions.jl/issues/34 is of interest because we are interested in the regularized versions for Bessel's functions.

I've also found that large x values lose some precision using that package, but need to flesh out further. I'm not for sure if they converge faster than the continued fractions approach we use in `besseli` though.

**Comment by oscardssmith** [comment]
The other thing to look at is whether https://fredrikj.net/blog/2021/12/computing-special-functions-using-numerical-integration/ can be used effectively.

**Comment by heltonmc** [comment]
To follow up on this. For `besselj` it can be calculated simply with...
```julia
using HypergeometricFunctions, SpecialFunctions
function besselj_hyper(v, x)
       a = HypergeometricFunctions.drummond0F1(v + 1, -x^2/4)
       return (x/2)^v / gamma(v+1) * a
end
```
Though, I'm not sure if there is a better method to do this. And I'm not sure stable/used HypergeometricFunctions.jl is...
I'm definitely in favor of incorporating this somehow just need to determine exactly when it is fast converging and when not to use. 
Definitely saves a lot of developer time...
